### ISSUE TITLE
No Message when phone rings

### ISSUE THREAD

**Issue by jjanderson** [sdesalve/hassio-addons#50]
Hi,

Thanks so much for this addon. I am using it in conjunction with 3cx and Amazon Polly here in the UK.

I am just experiencing something that maybe you could assist with?

I have setup Amazon Polly - quite a while ago as I use this for other services.

When I trigger the automation, the phone rings, but then there is no message coming through.

Could you give me some pointers as to what I could be doing wrong? Herewith my automation:

```
service: hassio.addon_stdin
data_template:
  addon: 89275b70_dss_voip
  input:
    call_sip_uri: sip:+REDACTED@XXX.3cx.co.uk
    message_tts: >-
      This is an automated Message. Patient does not appear to have had
      his Midday Meds
```

Many thanks

**Comment by sdesalve** [comment]
Hi,

Nat problems. Try to add 

--ip-addr

**Comment by jjanderson** [comment]
Thanks for the quick response. Where should I add this? in the addon config?

**Comment by sdesalve** [comment]
Yes.

Or if your setup will need, you can try to specify stun/ice server/proxy

**Comment by jjanderson** [comment]
I added this:
```
sip_parameters:
  caller_id_uri: sip:100@iotci.3cx.co.uk
  realm: '*'
  username: REDACTED
  password: REDACTED
platform_tts: amazon_polly
pjsua_custom_options: '--ip-addr=LOCAL IP ADDRESS OF LOCAL 3CX INSTANCE'
```
But then I got this:
```
12:12:22.382         os_core_unix.c !pjlib 2.9 for POSIX initialized
./run: line 337: echo: write error: Broken pipe
./run: line 337: echo: write error: Broken pipe
./run: line 337:   400 Exit 1                  ( sleep $MAX_CALL_TIME_VALUE; echo h; sleep 0.5; echo q )
       401 Segmentation fault      (core dumped) | ( pjsua --app-log-level=3 --config-file '/share/dss_voip/dss_pjsua.conf' $CALL_SIP_URI_VALUE 2> /share/dss_voip/dss_pjsua.log )
[Error] pjsua Exit code: 139
```

**Comment by sdesalve** [comment]
```
sip_parameters:
  caller_id_uri: sip:100@iotci.3cx.co.uk
  realm: '*'
  username: REDACTED
  password: REDACTED
platform_tts: amazon_polly
pjsua_custom_options: '--ip-addr=192.168.1.x'

```
