### ISSUE TITLE
Advice for sipgate.co.uk

### ISSUE THREAD

**Issue by alexd321** [sdesalve/hassio-addons#52]
Just in case its any use to anyone else, to get this working with sipgate.co.uk working on a Raspberry Pi 4 with HA OS I had to also add 

`--no-tcp`

to pjsua_custom_options

all options for reference:
```
sip_parameters:
  caller_id_uri: sip:12345678@sipgate.co.uk
  realm: '*'
  username: '12345678'
  password: MYPASS
  sip_parameters: sip:sipgate.co.uk
pjsua_custom_options: '--no-tcp'
```
