### ISSUE TITLE
parse error: Expected string key before ':' at line 1, column 4

### ISSUE THREAD

**Issue by LucaZiegler** [sdesalve/hassio-addons#77]
Hi,
I got with the following config this following error:

Config:

```
sip_parameters:
  caller_id_uri: sip:fritz1234@fritz.box:5060
  realm: "*"
  username: fritz1234
  password: PASSWORT
pjsua_custom_options: "--ip-addr=192.168.178.106"
```

Error Log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DSS VoIP Notifier
 VoIP Notifier for Home Assistant
-----------------------------------------------------------
 Add-on version: 4.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.7.1
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Starting addon...
PJSUA_CUSTOM_OPTIONS = '--ip-addr=192.168.178.106'
[Info] Listening for messages via stdin service call...
[Info] Received messages {"call_sip_uri":"sip:0171234567@fritz.box:5060","message_tts":"Achtung Feueralarm wurde ausgelöst. Bitte melden"}
parse error: Expected string key before ':' at line 1, column 4
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

The automation action:
```
service: hassio.addon_stdin
data:
  addon: 89275b70_dss_voip
  input:
    call_sip_uri: 'sip:0171234567@fritz.box:5060'
    message_tts: 'Achtung Feueralarm wurde ausgelöst. Bitte melden'
```

**Comment by LucaZiegler** [comment]
Sorry I found the issue.
I thought the tts integration was already active but I missed the following configuration.yaml code:

```
tts:
  - platform: google_translate
    service_name: google_translate_say
    language: 'de'
```
